config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#show'

  resources :estimations

  resource :simulation

  namespace :api do
    namespace :twilio do
      resources :messages
    end

    namespace :simulation do
      resources :probabilities
    end
  end
end

app/models/birth.rb
class Birth < ActiveRecord::Base

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :province

  enum :kind => [ :city, :municipality, :section ]

  def name
    name_fr
  end
end

app/models/mortality.rb
class Mortality < ActiveRecord::Base

end

app/models/province.rb
class Province < ActiveRecord::Base

  has_many :cities

  def self.find_by_zip_code(code)
    code = code.to_i

    if code.between?(1000, 1299)
      name = 'Bruxelles-Capitale'
    elsif code.between?(1300, 1499)
      name = 'Brabant wallon'
    elsif code.between?(1500, 1999)
      name = 'Brabant flamand'
    elsif code.between?(2000, 2999)
      name = 'Anvers'
    elsif code.between?(3000, 3499)
      name = 'Brabant flamand'
    elsif code.between?(3500, 3999)
      name = 'Limbourg'
    elsif code.between?(4000, 4999)
      name = 'Liège'
    elsif code.between?(5000, 5999)
      name = 'Namur'
    elsif code.between?(6000, 6599)
      name = 'Hainaut'
    elsif code.between?(6600, 6999)
      name = 'Luxembourg'
    elsif code.between?(7000, 7999)
      name = 'Hainaut'
    elsif code.between?(8000, 8999)
      name = 'Flandre occidentale'
    elsif code.between?(9000, 9999)
      name = 'Flandre orientale'
    end

    find_by_name_fr(name)
  end
end

app/controllers/api/simulation/probabilities_controller.rb
class Api::Simulation::ProbabilitiesController < ActionController::Base
  def index
    render :json => nil
  end

  def show
    render :json => {
      :birth                  => ProbabilityService.birth_probability,
      :male_death             => ProbabilityService.male_death_probability(params[:id]),
      :female_death           => ProbabilityService.female_death_probability(params[:id]),
      :male_migration         => ProbabilityService.male_migration_probability,
      :female_migration       => ProbabilityService.female_migration_probability,
      :male_age_repartition   => ProbabilityService.male_age_repartition,
      :female_age_repartition => ProbabilityService.female_age_repartition
    }
  end
end

app/controllers/api/twilio/messages_controller.rb
class Api::Twilio::MessagesController < ActionController::Base
  def index
    render :json => TwilioService.new.messages_list
  end

  def create
    failed = false
    sender = params[:From]
    body   = params[:Body].to_s.strip.split(' ')

    begin
      if body.size == 3
        age = body[0].to_i

        if age == 0
          failed = true
        else
          date_of_birth = Date.civil(Date.today.year - age, 1, 1)
          gender        = body[1].upcase == 'H' ? 'M' : 'F'
          zip           = body[2]
          province_id = Province.find_by_zip_code(zip).id
        end
      else
        failed = true
      end

      unless failed
        estimation = EstimationService.new(
          date_of_birth,
          gender,
          province_id
        ).estimate

        response = Twilio::TwiML::Response.new do |r|
          r.Message "Si nos calculs sont exacts, vous devriez mourir à #{estimation[:age]} ans."
        end
      end
    rescue
      failed = true
    end

    if failed
      response = Twilio::TwiML::Response.new do |r|
        r.Message "Message mal formaté ou données non-trouvées. Exemples : \"28 h 7000\" ou \"34 f 1020\"."
      end
    end

    render :text => response.text, :layout => false
  end

  def new
    create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/estimations_controller.rb
class EstimationsController < ApplicationController
  def create
    sleep 3

    begin
      city        = City.find(params[:city])
      province_id = Province.find_by_zip_code(city.zip)
      #date_of_birth = Date.parse(params[:date], "%Y-%m-%d")
      date_of_birth = Date.civil(params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i)

      @estimation = EstimationService.new(
        date_of_birth,
        params[:gender],
        province_id
      ).estimate
    rescue
      @error = "Données invalides."
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    params[:age]  ||= '18'
    params[:city] ||= City.find_by_name_fr('Mons').id
  end
end

app/controllers/simulations_controller.rb
class SimulationsController < ApplicationController
  def show
    render :layout => false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def age_options
    max_age = Mortality.pluck(:age).max

    (0..max_age).to_a.collect do |age|
      ["#{age} ans", age]
    end
  end

  def gender_options
    [
      ['Je suis un homme',   'M'],
      ['Je suis une femme', 'F'],
    ]
  end

  def city_options
    Province.order(:name_fr).collect do |province|
      cities = province.cities.order(:zip).collect do |city|
        [ "#{city.zip} — #{city.name_fr}", city.id ]
      end

      [ province.name_fr, cities ]
    end
  end
end

app/views/estimations/create.html.erb
<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <% if @error %>
      <div class="alert alert-danger">
        <%= @error %>
      </div>
    <% else %>
      <table class="table results">
        <tr>
          <th>Date de votre mort</th>
          <th>Age</th>
        </tr>

        <tr>
          <td><%= @estimation[:datetime_of_death].strftime('%d/%m/%Y %H:%M') %></td>
          <td><%= @estimation[:age] %></td>
        </tr>
      </table>
    <% end %>

    <a href="<%= root_path %>" class="btn btn-danger">Retour</a>
  </div>
</div>

app/views/home/show.html.erb
<a id="simulation" href="<%= simulation_path %>"><blink>Simulation visuelle</blink></a>

<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <div class="spinner">
      <%= image_tag 'reaper2.gif' %><br />
      <span style="color: #fff">Computing Death</span>
    </div>

    <%= form_tag estimations_path, { :class => 'form', :id => 'new_estimation' } do |f| %>
      <% cache do %>
        <div class="form-field date-of-birth">
          <%= label_tag :date_of_birth, "Quand êtes-vous né ?" %><br />
          <%#= date_field_tag :date_of_birth, '', { :class => 'form-control' } %>
          <%= select_date Date.today, { :start_year => Date.today.year - 104, :end_year => Date.today.year }, { :class => 'form-control' } %>
        </div>

        <div class="form-field">
          <%= label_tag :gender, "Quel est votre sexe ?" %>
          <%= select_tag :gender, options_for_select(gender_options, params[:gender]), :class => 'form-control' %>
        </div>

        <div class="form-field">
          <%= label_tag :city, "De quelle ville êtes-vous ?" %>
          <%= select_tag :city, grouped_options_for_select(city_options, params[:city]), :class => 'form-control' %>
        </div>
      <% end %>

      <div class="form-field">
        <%= button_tag 'Estimer mon espérance de vie', :class => 'btn btn-danger', :id => 'submit_estimation' %>
      </div>
    <% end %>

    <div class="sms">
      Envoyez votre âge, votre sexe et votre code postal au <span>+32 460 20 35 80</span> et recevez un pronostique mortel personnalisé (prix d'un SMS standard).
      <br />
      <small>Exemples : "28 h 7000" ou "34 f 1020".</small>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<% page_id = "#{params[:controller].gsub('/', '-')}-#{params[:action]}" %>

<html lang="en" id="<%= page_id %>">
  <head>
    <title>Mordatality</title>

    <%= stylesheet_link_tag :application %>
  </head>

  <body role="document">
    <a href="https://github.com/micdevcamp/mordatality"><img style="position: absolute; top: 0; left: 0; border: 0;" src="https://camo.githubusercontent.com/c6286ade715e9bea433b4705870de482a654f78a/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f6c6566745f77686974655f6666666666662e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_left_white_ffffff.png"></a>

    <div class="container" role="main">

      <div class="row">
        <div class="col-md-offset-4 col-md-4">
          <a href="<%= root_path %>"><%= image_tag 'logo.jpg', :id => 'logo' %></a>
        </div>
      </div>

      <%= yield %>
    </div> <!-- /container -->

    <%= javascript_include_tag :application %>
  </body>
</html>

app/views/simulations/show.html.erb
<!DOCTYPE html>

<% page_id = "#{params[:controller].gsub('/', '-')}-#{params[:action]}" %>

<html lang="en" id="<%= page_id %>">
  <head>
    <title>Mordatality</title>

    <%= stylesheet_link_tag :simulation %>
  </head>

  <body role="document" style="overflow:hidden">
    <div id="simulation" style="overflow:hidden"></div>

    <button type="button"
            class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal"
            style="position:absolute; bottom: 50px; left: 100px;display:none">
      Le jeu de la vie (le vrai !)<br/>
      <span style="font-size: 11px;display:block">Que suis-je en train de regarder ?</span>
    </button>

    <div id="myModal" class="modal fade">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Le jeu de la vie (le vrai !)</h4>
          </div>
          <div class="modal-body">
            <p>
              Ce petit outil a été développé dans le cadre du <a href="http://www.softlab.be/summercamp">MIC Summer Camp 2015</a>.
            </p>

            <p>
              Présentation finale du projet : <a target="_blank" href="/presentation-summercamp2015.pdf">presentation-summercamp2015.pdf</a>
            </p>

            <h3>Explications</h3>

            <p>
              <ul>
                <li>
                  Chaque point représente environ 11 000 Belges (1000 points pour toute la population).
                </li>
                <li>
                  Les points sont positionnés selon la pyramide des âges actuelle (hommes/femmes).
                </li>
                <li>
                  Les points disparaissent lors d'un décès (probabilités de décès pour homme/femme selon son âge)
                </li>
                <li>
                  Les points apparaissent à gauche lors d'une naissance (probabilités de donner naissance pour une femme selon son âge)
                </li>
                <li>
                  Les points apparaissent et disparaissent selon les migrations (probabilités d'immigration et d'émigration hommes/femmes).
                </li>
              </ul>
            </p>
          </div>
          <div class="modal-footer" style="text-align:left">
            <ul>
              <li>
                <a href="?modal=0">
                  Relancer la simulation.
                </a>
              </li>
              <li>
                <a href="?modal=0&type=no-migration">
                  Relancer la simulation sans prendre en compte l'immigration et de l'émigration.
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <%= javascript_include_tag :application %>
  </body>
</html>